services:
  mongodb:
    image: mongo:8.0-noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    command: [ --bind_ip_all ]

volumes:
  mongodb:
