services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis-service
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    environment:
      - REDIS_PASSWORD=password
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

volumes:
  redisdata:

